In [1]:
import tensorflow as tf
tf.executing_eagerly()

True

In [2]:
x = [[10.]]

res = tf.matmul(x, x)

res

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[100.]], dtype=float32)>

In [3]:
a = tf.constant([[10, 20],
                [30, 40]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [4]:
b = tf.add(a, 2)

b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 22],
       [32, 42]])>

In [5]:
print(a * b)

tf.Tensor(
[[ 120  440]
 [ 960 1680]], shape=(2, 2), dtype=int32)


In [6]:
m = tf.Variable([4.0, 5.0, 6.0], tf.float32, name = "m")
c = tf.Variable([1.0, 1.0, 1.0], tf.float32, name = "c")

In [7]:
# since eager exec, place holder concept not exist
x = tf.Variable([100.0, 100.0, 100.0], tf.float32, name = "x")

x

<tf.Variable 'x:0' shape=(3,) dtype=float32, numpy=array([100., 100., 100.], dtype=float32)>

In [8]:
y = m * x + c

y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([401., 501., 601.], dtype=float32)>